# Generated by Django 4.1.1 on 2022-09-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_manager', '0003_auto_20201030_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenlookupid',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tokenlookupid',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
