# Generated by Django 4.1.1 on 2022-09-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_manager', '0004_alter_tokenlookupid_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenlookupid',
            name='r_type',
        ),
        migrations.AddField(
            model_name='tokenlookupid',
            name='device_type',
            field=models.CharField(blank=True, choices=[('Mobile', 'Mobile'), ('Tablet', 'Tablet'), ('PC', 'PC'), ('Bot', 'Bot'), ('Other', 'Other')], help_text='ex: Mobile', max_length=6, null=True, verbose_name='Device Type'),
        ),
        migrations.AlterField(
            model_name='tokenlookupid',
            name='browser',
            field=models.CharField(blank=True, help_text='ex: Chrome Mobile WebView 103.0.50', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tokenlookupid',
            name='device',
            field=models.CharField(blank=True, help_text='ex: Samsung SM-A505F', max_length=100, null=True, verbose_name='Device'),
        ),
        migrations.AlterField(
            model_name='tokenlookupid',
            name='ip',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='tokenlookupid',
            name='os',
            field=models.CharField(blank=True, help_text='ex: Android', max_length=300, null=True, verbose_name='OS Name'),
        ),
    ]
